// Novedades por versión (Perfil > Aplicación). Versión x.y.z: x = cambio grande (sección nueva, rediseño general o algo
// que deja de ser compatible), y = funcionalidad nueva o mejora visible, z = correcciones y ajustes menores.
// La PRIMERA entrada debe coincidir con CACHE_VERSION de sw.js (lo comprueba tools/verify_perfil.html).
// El historial anterior a 3.16.0 se reconstruyó a partir de git el 2026-09-24 (antes solo había un contador v1…v296).
export const NOVEDADES = [
  { version: "3.22.0", fecha: "2026-09-25", cambios: ["Nueva calculadora «Valoración integral»: evalúa de 1 a 6 escenarios de conductor (tensión, conductor y conductores por fase) para una misma conexión, con ampacidad aérea o subterránea, pérdidas, regulación, cortocircuito y costo total actualizado, y dice cuáles cumplen y cuál conviene."] },
  { version: "3.21.1", fecha: "2026-09-24", cambios: ["Ampacidad aérea: la casilla «Calcular con la posición del sol» pasa al final de la tarjeta de radiación solar, debajo de Qse y θ."] },
  { version: "3.21.0", fecha: "2026-09-24", cambios: ["Ampacidad aérea: la radiación solar (Qse) y el ángulo de incidencia (θ) se pueden calcular con la posición del sol a partir de la latitud, la fecha, la hora solar y la dirección de la línea, con un botón que busca el peor día del año.", "Ampacidad subterránea: con cable monopolar y puesta a tierra unipuntual se puede dimensionar el conductor de continuidad de tierra (GCC): área mínima en mm² y calibre comercial sugerido."] },
  { version: "3.20.1", fecha: "2026-09-24", cambios: ["Ampacidad subterránea: nota en Fórmulas que explica dónde aparece la tensión inducida en la pantalla con puesta a tierra unipuntual y con cross-bonding."] },
  { version: "3.20.0", fecha: "2026-09-24", cambios: ["Conductor económico: nueva sección «¿Puede el costo de instalación cambiar la decisión?», que dice, para cada alternativa, hasta cuánto puede costar de más instalar la opción ganadora sin que deje de ser la mejor, y avisa cuándo revisarlo según el peso de los conductores."] },
  { version: "3.19.9", fecha: "2026-09-24", cambios: ["Conductor económico: la sensibilidad al costo de instalación destaca el margen por km de cada alternativa y resume la ventaja, el porqué y cuándo cambia la conclusión."] },
  { version: "3.19.8", fecha: "2026-09-24", cambios: ["Conductor económico: la sensibilidad al costo de instalación se explica paso a paso para cada alternativa (por cuánto gana la mejor opción, por qué, y cuánto tendría que cambiar la instalación para que perdiera)."] },
  { version: "3.19.7", fecha: "2026-09-24", cambios: ["Conductor económico: la sensibilidad al costo de instalación muestra la ventaja por km de la opción ganadora, y la otra sensibilidad se llama «Sensibilidad a los supuestos del análisis»."] },
  { version: "3.19.6", fecha: "2026-09-24", cambios: ["Conductor económico: la sensibilidad al costo de instalación va al final, con una explicación más clara, y el resultado ya no anida paréntesis.", "Ampacidad aérea: notas de las fórmulas más claras."] },
  { version: "3.19.5", fecha: "2026-09-24", cambios: ["Perfil > Aplicación: la lista de novedades solo la ve el administrador; «Uso sin conexión» ya no menciona el número de archivos.", "Perfil > Calculadoras: más espacio antes de cada separador de sección.", "Inicio de sesión: aclara que con una cuenta autorizada también se habilita la configuración avanzada."] },
  { version: "3.19.4", fecha: "2026-09-24", cambios: ["«Agregar registro» pasa al final de la línea de filtros de cada catálogo.", "Perfil > Calculadoras: espacios entre campos iguales a los de las calculadoras y una línea divisoria entre secciones."] },
  { version: "3.19.3", fecha: "2026-09-24", cambios: ["Perfil > Catálogos: cada catálogo tiene su botón «Historial», que abre sus versiones justo debajo; en el celular cada catálogo se muestra como un bloque.", "«Agregar registro» ya no va destacado (solo «Guardar y publicar»)."] },
  { version: "3.19.2", fecha: "2026-09-24", cambios: ["Cortocircuito: descripción más corta de la constante k₁."] },
  { version: "3.19.1", fecha: "2026-09-24", cambios: ["Regulación: el reporte incluye la reactancia inductiva y la impedancia efectiva de cada tramo.", "Cortocircuito: la constante k₁ ahora explica qué representa.", "Ajustes de texto en las notas de las fórmulas de Ocupación de ductos, Regulación y Cortocircuito."] },
  { version: "3.19.0", fecha: "2026-09-24", cambios: ["El administrador puede agregar, editar y eliminar registros de los catálogos de conductores, tuberías y resoluciones; los cambios se publican de inmediato para todos.", "Perfil > Catálogos guarda las últimas 10 versiones de cada catálogo y permite volver a cualquiera de ellas."] },
  { version: "3.18.0", fecha: "2026-09-24", cambios: ["Los catálogos (conductores, tuberías y resoluciones) se pueden actualizar desde el servidor sin publicar una versión nueva de la app; sin internet se usa la última copia descargada.", "Perfil: el administrador publica los catálogos en la pestaña Catálogos."] },
  { version: "3.17.0", fecha: "2026-09-24", cambios: ["Pérdidas y Regulación quedan disponibles sin iniciar sesión, como Ocupación de ductos."] },
  { version: "3.16.3", fecha: "2026-09-24", cambios: ["Ayuda: la tarjeta del desarrollador muestra la versión real de la aplicación."] },
  { version: "3.16.2", fecha: "2026-09-24", cambios: ["Regulación: el factor de potencia inicial pasa de 0.95 a 0.9, igual que en Pérdidas y Conductor económico.", "Corriente de conductores NTC 2050: se quita la nota debajo de la tabla.", "Conversión de coordenadas: los ejemplos del cuadro por lotes muestran primero los formatos con espacio."] },
  { version: "3.16.1", fecha: "2026-09-24", cambios: ["Uso sin conexión: la app descarga sola los archivos que le falten al abrir Perfil > Aplicación con internet, y si alguno no se puede descargar dice cuál.", "Al actualizar, cada archivo se descarga por separado y siempre la copia recién publicada."] },
  { version: "3.16.0", fecha: "2026-09-24", cambios: ["Perfil: nuevas pestañas Calculadoras (valores con que arranca cada calculadora), Datos (respaldo y borrado de lo guardado en este dispositivo) y Aplicación (versión y «Buscar actualización»).","La aplicación ahora se numera por versiones (x.y.z) con esta lista de novedades."] },
  { version: "3.15.0", fecha: "2026-09-24", cambios: ["Corriente de conductores NTC 2050: el encabezado de la tabla queda fijo y las filas se desplazan debajo."] },
  { version: "3.14.0", fecha: "2026-09-24", cambios: ["Conversión de unidades, conversión de coordenadas y las pantallas de IA recuerdan lo escrito al cambiar de pantalla."] },
  { version: "3.13.0", fecha: "2026-09-23", cambios: ["Pérdidas, Regulación, Cortocircuito y Conductor económico: se elige la referencia (construcción) del conductor aéreo."] },
  { version: "3.12.0", fecha: "2026-09-23", cambios: ["Asistente técnico: Agente riguroso para memorias de cálculo, con ficha de datos del proyecto."] },
  { version: "3.11.0", fecha: "2026-09-23", cambios: ["Funciones con IA: además de Gemini, se puede usar OpenAI (ChatGPT) o Anthropic (Claude)."] },
  { version: "3.10.0", fecha: "2026-09-21", cambios: ["Calculadoras: las tarjetas se pueden plegar y desplegar."] },
  { version: "3.9.0", fecha: "2026-09-21", cambios: ["Calculadora nueva: Conductor económico (costo total actualizado de varias opciones de conductor)."] },
  { version: "3.8.0", fecha: "2026-09-20", cambios: ["Reporte de la IA: descarga en Word (.docx) y Markdown."] },
  { version: "3.7.0", fecha: "2026-09-20", cambios: ["IA: herramientas de diseño (dimensionar y verificar conductores) para agentes propios."] },
  { version: "3.6.0", fecha: "2026-09-20", cambios: ["Ocupación de ductos: corte transversal del ducto y dona de ocupación."] },
  { version: "3.5.0", fecha: "2026-09-19", cambios: ["Catálogo nuevo: Tuberías."] },
  { version: "3.4.0", fecha: "2026-09-19", cambios: ["Conversión de coordenadas entre cualquier par de ~500 sistemas EPSG, también por lotes."] },
  { version: "3.3.0", fecha: "2026-09-19", cambios: ["Conversión de unidades: modo completo con 19 categorías."] },
  { version: "3.2.0", fecha: "2026-09-19", cambios: ["Perfil: color principal personal para cada tema."] },
  { version: "3.1.0", fecha: "2026-09-19", cambios: ["Niveles de acceso: visitante, usuario y administrador."] },
  { version: "3.0.0", fecha: "2026-09-19", cambios: ["Rediseño de las calculadoras: tarjetas, varios tramos, fórmulas y reportes para copiar."] },
  { version: "2.0.0", fecha: "2026-09-18", cambios: ["Sección nueva Funciones con IA (Corrector de redacción y Asistente técnico) e inicio de sesión con Google."] },
  { version: "1.0.0", fecha: "2026-08-22", cambios: ["Primera versión web: calculadoras, catálogos y normatividad, también sin conexión."] },
];
